export const VISUAL_PROFILE = 'premium_arcade_v2';

export const POSTFX_PRESETS = {
    premium_arcade_v2: {
        toneMappingExposure: 1.65,
        bloom: {
            strength: { lowPower: 0.15, normal: 0.22 },
            radius: { lowPower: 0.3, normal: 0.4 },
            threshold: { lowPower: 0.5, normal: 0.55 },
        },
        vignette: {
            innerStopPct: 64,
            outerAlpha: 0.2,
        },
        adaptive: {
            sampleWindowSec: 3.5,
            fpsThreshold: 49,
            pixelRatioStep: 0.2,
            bloomDegradeScale: 0.74,
        },
    },
};

export const LIGHTING_PRESETS = {
    premium_arcade_v2: {
        levels: [
            {
                ground: 0x7ec850,
                fog: 0x87CEEB,
                fogDensity: 0.005,
                ambient: 0xffffff,
                ambientIntensity: 0.95,
                dirLight: 0xfffcf0,
                dirIntensity: 1.55,
                sky: 0x87CEEB,
                fillFactor: 0.4,
                hemiIntensity: 0.65,
                rimIntensity: 0.45,
                ringOpacity: 0.28,
                discOpacity: 0.1,
            },
            {
                ground: 0xd4a056,
                fog: 0xc9a95a,
                fogDensity: 0.0076,
                ambient: 0xfff0d0,
                ambientIntensity: 0.58,
                dirLight: 0xffe0a0,
                dirIntensity: 0.94,
                sky: 0xd4a060,
                fillFactor: 0.28,
                hemiIntensity: 0.44,
                rimIntensity: 0.22,
                ringOpacity: 0.27,
                discOpacity: 0.09,
            },
            {
                ground: 0xe8e8f0,
                fog: 0xd0d8e8,
                fogDensity: 0.0088,
                ambient: 0xd0d8ff,
                ambientIntensity: 0.74,
                dirLight: 0xeeeeff,
                dirIntensity: 0.86,
                sky: 0xb0c0d0,
                fillFactor: 0.3,
                hemiIntensity: 0.52,
                rimIntensity: 0.26,
                ringOpacity: 0.26,
                discOpacity: 0.09,
            },
            {
                ground: 0x1a3a1a,
                fog: 0x0a0a2a,
                fogDensity: 0.0106,
                ambient: 0x4444aa,
                ambientIntensity: 0.36,
                dirLight: 0x8888cc,
                dirIntensity: 0.56,
                sky: 0x0a0a2a,
                fillFactor: 0.32,
                hemiIntensity: 0.38,
                rimIntensity: 0.28,
                ringOpacity: 0.3,
                discOpacity: 0.12,
            },
            {
                ground: 0x3a2a1a,
                fog: 0x4a1a0a,
                fogDensity: 0.0079,
                ambient: 0xff6633,
                ambientIntensity: 0.44,
                dirLight: 0xff8844,
                dirIntensity: 1.2,
                sky: 0x2a0a00,
                fillFactor: 0.27,
                hemiIntensity: 0.4,
                rimIntensity: 0.25,
                ringOpacity: 0.31,
                discOpacity: 0.11,
            },
        ],
        ground: {
            size: 200,
            segments: 40,
            grassPatchCount: { lowPower: 26, normal: 40 },
            tuftCount: { lowPower: 52, normal: 80 },
            flowerCount: { lowPower: 18, normal: 30 },
        },
        path: {
            steps: 16,
            jitter: 0.62,
            radius: { min: 0.45, max: 0.82 },
            opacity: 0.085,
            yBase: 0.012,
            yStep: 0.00022,
        },
        zones: {
            ringWidth: 0.18,
            ringEmissiveMul: 0.58,
            ringIntensity: 0.44,
            discEmissiveMul: 0.28,
            discIntensity: 0.26,
            yRing: 0.03,
            yDisc: 0.019,
        },
        beacons: {
            truckLightIntensity: 1.15,
            houseLightIntensity: 1.0,
            truckRadius: 16,
            houseRadius: 17,
            truckPulse: { speed: 2.9, amount: 0.2 },
            housePulse: { speed: 2.4, amount: 0.22, phase: 1.3 },
        },
        particles: {
            size: 0.14,
            opacity: 0.62,
        },
    },
};

export const UI_PRESETS = {
    premium_arcade_v2: {
        timings: {
            fastMs: 170,
            baseMs: 240,
            slowMs: 340,
            toastMs: 1500,
            announcementMs: 2000,
            floatPointMs: 1200,
        },
        cssVars: {
            '--ui-motion-fast': '170ms',
            '--ui-motion-base': '240ms',
            '--ui-motion-slow': '340ms',
            '--ui-overlay-blur': '10px',
            '--ui-grid-opacity': '0.42',
            '--ui-card-border': 'rgba(154, 215, 247, 0.32)',
            '--ui-card-shadow': '0 20px 45px rgba(0, 0, 0, 0.46)',
            '--hud-pill-border': 'rgba(204, 239, 255, 0.3)',
        },
    },
};

export const PLAYER_MOTION_PRESETS = {
    premium_arcade_v2: {
        blendSpeed: 7.5,
        walkStride: 0.66,
        carryStride: 0.44,
        walkArmSwing: 0.54,
        carryArmSwing: 0.22,
        carryArmLift: 0.2,
        idleBreath: 0.03,
        pickupKickDecay: 2.8,
        dropSettleDecay: 2.2,
        bodyLean: 0.14,
        headNod: 0.05,
    },
};
